export const constant = {
  ACCESS_TOKEN: 'ACCESS_TOKEN',
  REFRESH_TOKEN: 'REFRESH_TOKEN',
  CLIENT_ID: 'client_id',
  CLIENT_SECRET: 'client_secret',
  GRANT_TYPE: 'grant_type',
  PHONE: 'Phone',
  PASSWORD: 'Password',
  AUTHORIZATION: 'Authorization',
  BEARER: 'Token ',
  CONTENT_TYPE: 'Content-Type',
  ACCEPT: 'Accept',
  CONTENT_TYPE_JSON: 'application/json',
  CONTENT_TYPE_FORM_DATA: 'multipart/form-data',
  CONTENT_TYPE_X_WWW_FORM_URLENCODED: 'application/x-www-form-urlencoded',
  FILE: 'file',
  FILE_NAME: 'file_name',
  FILE_TYPE: 'file_type',
  TYPE: 'document_type',
  API_URL: {
    TOKEN: '/login',
    NOTIFICATIONS: '/send_notifications',
  },
  SUCCESS: 'success',
};
